#!/bin/bash

count_1=$( egrep -c ${1} ${2} )
count_2=$( egrep -c ${1} ${3} )

if [ ${count_1} -gt ${count_2} ];then
    echo "${2}"
elif [ ${count_1} -lt ${count_2} ];then
    echo "${3}"
else
    echo "${2} ${3}"
fi

