#!/bin/bash

if [ ${#} -ne 1 ];then
	echo "Invalid number of arguments" >&2
	exit 1
fi
size=0
largest=""
for i in $(cat ${1})
do
if [ ${#i} -gt ${size} ];then
	largest=${i}
	size=${#i}
fi
done

echo "${largest}"
echo "${size}"

